name: Auto Mining Off

on:
  workflow_dispatch:        # API (cron-job.org) ya Manual trigger ke liye

jobs:
  auto-off:
    runs-on: ubuntu-latest

    steps:
      - name: Keep GitHub Actions Active (Ping GitHub API)
        run: curl -I https://api.github.com

      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run auto mining off script
        run: node auto_mining_off.js
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          
